import { Component, inject, input, signal, type OnDestroy } from '@angular/core';
import type { RealtimeChannel } from '@supabase/supabase-js';
import { freesoundApiKey } from '../../../environments/freesound';
import { AuthService } from '../../core/services/auth.service';

interface Sonido { id: number; name: string; username: string; license: string; previews: Record<string, string>; }

@Component({ selector: 'app-ambiente-panel', template: `
  <div class="ambiente"><button class="btn" (click)="toggleActivacion()">{{ activado() ? 'Desactivar sonido' : 'Activar sonido' }}</button>@if (compartido(); as s) { <div class="reproductor"><strong>{{s.name}}</strong><button class="btn ghost" (click)="toggleLocal(s)">{{ actual() === s.id ? 'Pausa' : '▶' }}</button><button class="btn ghost" title="Quitar ambiente de la partida" (click)="quitarCompartido()">×</button><input class="volumen" type="range" min="0" max="1" step="0.05" [value]="volumen()" [style.--volumen]="volumen() * 100 + '%'" (input)="cambiarVolumen($any($event.target).value)" aria-label="Volumen local" /></div> }<form (submit)="buscar($event)"><input #q placeholder="Bosque, castillo, lluvia…" /><button class="btn">Buscar</button></form>
  @if (error(); as e) { <p class="error">{{e}}</p> }
  @for (s of resultados(); track s.id) { <div class="sonido"><button class="nombre" (click)="reproducir(s)">{{ s.name }}</button>@if (!esCC0(s.license)) { <details><summary>Créditos y licencia</summary><small>{{s.username}} · {{licencia(s.license)}}</small></details> }<button class="btn ghost" (click)="reproducir(s)">{{ actual() === s.id ? 'Pausa' : '▶' }}</button>@if (actual() === s.id) { <input class="volumen" type="range" min="0" max="1" step="0.05" [value]="volumen()" [style.--volumen]="volumen() * 100 + '%'" (input)="cambiarVolumen($any($event.target).value)" aria-label="Volumen" /> }</div> }
  </div>`, styles: `
  .ambiente{display:flex;flex-direction:column;gap:.45rem}.ambiente form{display:flex;gap:.3rem}.ambiente input{min-width:0}.error{color:var(--danger);margin:0}.reproductor{display:grid;grid-template-columns:1fr auto;gap:.3rem;padding:.45rem;border:1px solid var(--accent);border-radius:var(--radius);background:var(--surface-2)}.sonido{display:grid;grid-template-columns:1fr auto;gap:.1rem .4rem;padding:.35rem;border-bottom:1px solid var(--border)}.nombre{background:none;border:0;color:var(--text);text-align:left;padding:0;cursor:pointer}.sonido small,details{color:var(--muted);font-size:.7rem}summary{cursor:pointer}.volumen{grid-column:1/-1;width:100%;height:.7rem;padding:0;appearance:none;background:transparent;cursor:pointer}.volumen::-webkit-slider-runnable-track{height:.35rem;border-radius:999px;background:linear-gradient(to right,var(--accent) 0 var(--volumen,70%),var(--border) var(--volumen,70%) 100%)}.volumen::-webkit-slider-thumb{appearance:none;width:1rem;height:1rem;margin-top:-.32rem;border:2px solid var(--surface);border-radius:50%;background:var(--accent-strong);box-shadow:0 1px 4px var(--sombra)}.volumen::-moz-range-track{height:.35rem;border-radius:999px;background:var(--border)}.volumen::-moz-range-progress{height:.35rem;border-radius:999px;background:var(--accent)}.volumen::-moz-range-thumb{width:.8rem;height:.8rem;border:2px solid var(--surface);border-radius:50%;background:var(--accent-strong)}
  ` })
export class AmbientePanelComponent implements OnDestroy {
  readonly partyId=input.required<string>(); private auth=inject(AuthService); private canal:RealtimeChannel|null=null;
  readonly activado=signal(false); readonly compartido=signal<Sonido|null>(null);
  readonly resultados=signal<Sonido[]>([]); readonly error=signal<string|null>(null); readonly actual=signal<number|null>(null); readonly volumen=signal(.7); private audio=new Audio();
  async buscar(e:Event) { e.preventDefault(); const q=(e.target as HTMLFormElement).querySelector('input')!.value.trim(); if(!q) return; if(!freesoundApiKey || freesoundApiKey.startsWith('PEGAR_')){this.error.set('Pegá tu clave de Freesound en src/environments/freesound.local.ts.');return;} this.error.set(null); try { const u=`https://freesound.org/apiv2/search/text/?query=${encodeURIComponent(q)}&fields=id,name,username,license,previews&page_size=12&token=${encodeURIComponent(freesoundApiKey)}`; const r=await fetch(u); if(!r.ok) throw new Error('Freesound rechazó la búsqueda.'); const d=await r.json();this.resultados.set(d.results??[]);}catch{this.error.set('No se pudo buscar en Freesound.');} }
  ngOnInit(){ void this.cargarCompartido(); }
  async toggleActivacion(){if(this.activado()){this.activado.set(false);this.audio.pause();this.actual.set(null);return;}this.activado.set(true);const s=this.compartido();if(s)this.sonar(s);}
  async cargarCompartido(){const c=this.auth.client;if(!c)return;const {data}=await c.from('party_audio_state').select('sound').eq('party_id',this.partyId()).maybeSingle();if(data?.sound)this.compartido.set(data.sound as Sonido);this.canal=c.channel(`party-audio:${this.partyId()}`).on('postgres_changes',{event:'*',schema:'public',table:'party_audio_state',filter:`party_id=eq.${this.partyId()}`},p=>{const s=(p.new as {sound?:Sonido}).sound??null;this.compartido.set(s);if(s&&this.activado())this.sonar(s);}).subscribe();}
  reproducir(s:Sonido) { if(this.actual()===s.id){this.audio.pause();this.actual.set(null);return;} void this.elegirCompartido(s); }
  private async elegirCompartido(s:Sonido){const c=this.auth.client;const u=this.auth.userId();if(!c||!u)return;await c.from('party_audio_state').upsert({party_id:this.partyId(),author_id:u,sound:s});this.compartido.set(s);if(this.activado())this.sonar(s);}
  async quitarCompartido(){const c=this.auth.client;if(!c)return;await c.from('party_audio_state').delete().eq('party_id',this.partyId());this.compartido.set(null);this.audio.pause();this.actual.set(null);}
  private sonar(s:Sonido){this.audio.src=s.previews['preview-hq-mp3']??s.previews['preview-lq-mp3'];this.audio.volume=this.volumen();void this.audio.play();this.actual.set(s.id);}
  toggleLocal(s: Sonido) { if (this.actual() === s.id) { this.audio.pause(); this.actual.set(null); } else this.sonar(s); }
  cambiarVolumen(valor: string) { const volumen = Number(valor); this.volumen.set(volumen); this.audio.volume = volumen; }
  licencia(l:string){return l.includes('Zero')?'CC0':l.includes('Attribution')?'CC BY':l;}
  esCC0(l:string){return this.licencia(l) === 'CC0';}
  ngOnDestroy() { this.audio.pause(); this.audio.src = '';if(this.canal&&this.auth.client)void this.auth.client.removeChannel(this.canal); }
}
